// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tweetero.API.DbContexts;

#nullable disable

namespace Tweetero.API.Migrations
{
    [DbContext(typeof(TweeteroContext))]
    [Migration("20230709133834_SetsAuthentication")]
    partial class SetsAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tweetero.API.Entities.Tweet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tweets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "I love crunchy lettuce!",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Message = "I hate when I get alone... :(",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Message = "Testing second user",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Tweetero.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://www.racoesreis.com.br/wordpress/wp-content/uploads/cachorro-origem3.jpg",
                            Password = "AQAAAAEAACcQAAAAEBfUqsmn6PYi0kBuwDKnFIRi4Jp9lGOg04DDOB7pnSOQLPQQLsqNkyWJfgjsb6B2gw==",
                            Username = "test"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://www.racoesreis.com.br/wordpress/wp-content/uploads/cachorro-origem3.jpg",
                            Password = "AQAAAAEAACcQAAAAEEInRuW4i8YHtX6v2hCLT1aCfK8u0+1yfdO+v4r/FVh5D0RjucaijvArS8jdWTZuWw==",
                            Username = "test2"
                        });
                });

            modelBuilder.Entity("Tweetero.API.Entities.Tweet", b =>
                {
                    b.HasOne("Tweetero.API.Entities.User", "User")
                        .WithMany("Tweets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tweetero.API.Entities.User", b =>
                {
                    b.Navigation("Tweets");
                });
#pragma warning restore 612, 618
        }
    }
}
